<?php
/**
 * ApiJormungandrStakePoolTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanowallet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccann\cardanowallet;

use PHPUnit\Framework\TestCase;

/**
 * ApiJormungandrStakePoolTest Class Doc Comment
 *
 * @category    Class
 * @description ApiJormungandrStakePool
 * @package     melmccann\cardanowallet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiJormungandrStakePoolTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiJormungandrStakePool"
     */
    public function testApiJormungandrStakePool()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "metrics"
     */
    public function testPropertyMetrics()
    {
    }

    /**
     * Test attribute "apparent_performance"
     */
    public function testPropertyApparentPerformance()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "margin"
     */
    public function testPropertyMargin()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "saturation"
     */
    public function testPropertySaturation()
    {
    }

    /**
     * Test attribute "desirability"
     */
    public function testPropertyDesirability()
    {
    }
}
