<?php
/**
 * ByronWalletsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ByronWalletsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ByronWalletsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteByronWallet
     *
     * Delete.
     *
     */
    public function testDeleteByronWallet()
    {
    }

    /**
     * Test case for getByronUTxOsStatistics
     *
     * UTxO Statistics.
     *
     */
    public function testGetByronUTxOsStatistics()
    {
    }

    /**
     * Test case for getByronWallet
     *
     * Get.
     *
     */
    public function testGetByronWallet()
    {
    }

    /**
     * Test case for listByronWallets
     *
     * List.
     *
     */
    public function testListByronWallets()
    {
    }

    /**
     * Test case for postByronWallet
     *
     * Restore.
     *
     */
    public function testPostByronWallet()
    {
    }

    /**
     * Test case for putByronWallet
     *
     * Update Metadata.
     *
     */
    public function testPutByronWallet()
    {
    }

    /**
     * Test case for putByronWalletPassphrase
     *
     * Update Passphrase.
     *
     */
    public function testPutByronWalletPassphrase()
    {
    }
}
