<?php
/**
 * WalletsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\cardanowallet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cardano Wallet Backend API
 *
 * <p align=\"right\"><img style=\"position: relative; top: -10em; margin-bottom: -12em;\" width=\"20%\" src=\"https://cardanodocs.com/img/cardano.png\"></img></p>
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace melmccann\cardanowallet;

use \melmccann\cardanowallet\Configuration;
use \melmccann\cardanowallet\ApiException;
use \melmccann\cardanowallet\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WalletsApiTest Class Doc Comment
 *
 * @category Class
 * @package  melmccann\cardanowallet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WalletsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteWallet
     *
     * Delete.
     *
     */
    public function testDeleteWallet()
    {
    }

    /**
     * Test case for getUTxOsStatistics
     *
     * UTxO Statistics.
     *
     */
    public function testGetUTxOsStatistics()
    {
    }

    /**
     * Test case for getWallet
     *
     * Get.
     *
     */
    public function testGetWallet()
    {
    }

    /**
     * Test case for listWallets
     *
     * List.
     *
     */
    public function testListWallets()
    {
    }

    /**
     * Test case for postWallet
     *
     * Create / Restore.
     *
     */
    public function testPostWallet()
    {
    }

    /**
     * Test case for putWallet
     *
     * Update Metadata.
     *
     */
    public function testPutWallet()
    {
    }

    /**
     * Test case for putWalletPassphrase
     *
     * Update Passphrase.
     *
     */
    public function testPutWalletPassphrase()
    {
    }
}
